# This file was generated by GoReleaser. DO NOT EDIT.
class Casec < Formula
  desc "A text case converter"
  homepage "https://github.com/mingrammer/casec"
  url "https://github.com/mingrammer/casec/releases/download/v0.1.3/casec_0.1.3_darwin_amd64.tar.gz"
  version "0.1.3"
  sha256 "7aadc80dbe10b3c96252ce00b9a32ef462eff166829f54c6200287d33b1c20d9"

  def install
    bin.install "casec"
  end

  test do
    system "#{bin}/casec -v"
  end
end
